name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  pull_request:
  push:
    paths:
      - '**.agda'
      - '*.agda-lib'
      - '.github/workflows/**.yml'
    branches: [master]
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.4
          stdlib-version: 2.0
          main: Lenses
          libraries: |
            omelkonian/agda-stdlib-classes#v2.0
            omelkonian/agda-stdlib-meta#v2.0
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          measure-typechecking: true
