name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
  pull_request:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.4
          stdlib-version: 2.0-rc1
          main: Lenses
          libraries: |
            omelkonian/agda-stdlib-classes#v2.0-rc1
            omelkonian/agda-stdlib-meta#v2.0-rc1
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          measure-typechecking: true
